### ISSUE TITLE
[Q] Detach window for manual resize?

### ISSUE THREAD

**Issue by tuyenpm9** [halfwit/hwwm#1]
Look promising to me for use hwwm, haven't tried it yet, but this is a question that can we map a key with sxhkd to detach a window for resize it manually? this is for more flexible use.

**Comment by halfwit** [comment]
You certainly can. You would not list that particular window title in your
windows file, and run a simple window manager that handles mouse movement,
and hwwm inside of that.

**Comment by tuyenpm9** [comment]
Thanks.
